#! /bin/bash

if [ $# -lt 1 ]
then
        echo "mycli <command>"
        echo
        echo "Commands:"
        echo
        echo "list -- list databases"
        echo "create -- create new database and, optionally, database user"
        echo "makeuser -- create user and grant privileges"
        echo "export -- export database to sql file"
        exit
fi

mysqlLogin=""
mysqlPassword=""

if [ -z "$mysqlLogin" ]; then
    read -p "MySQL Login: " mysqlLogin    
fi
if [ -z "$mysqlPassword" ]; then
    read -p "MySQL Password: " mysqlPassword
fi

case "$1" in
    'list')
        mysql --user="$mysqlLogin" --password="$mysqlPassword" --execute="SHOW DATABASES;"
    ;;
    'create')
        read -p "Database name: " dbName
        mysql --user="$mysqlLogin" --password="$mysqlPassword" --execute="CREATE DATABASE $dbName;"
        read -p "Database user [press enter for none]: " dbUser
        if [ ! -z "$dbUser" ]; then
            read -p "Database user password: " dbPass
            mysql --user="$mysqlLogin" --password="$mysqlPassword" --execute="CREATE USER '$dbUser'@'localhost' IDENTIFIED BY '$dbPass'; GRANT ALL PRIVILEGES ON $dbName.* TO '$dbUser'@'localhost'; FLUSH PRIVILEGES;";
        fi
    ;;
    'makeuser')
        read -p "Database user [press enter for none]: " dbUser
        read -p "Grant privileges on: " dbName
        if [ ! -z "$dbUser" ]; then
            read -p "Database user password: " dbPass
            mysql --user="$mysqlLogin" --password="$mysqlPassword" --execute="CREATE USER '$dbUser'@'localhost' IDENTIFIED BY '$dbPass'; GRANT ALL PRIVILEGES ON $dbName.* TO '$dbUser'@'localhost'; FLUSH PRIVILEGES;";
        fi
    ;;
    'export')
        if [ ! -z "$2" ]; then
            dbName="$2"
        else
            read -p "Database name: " dbName
        fi
        mysqldump -u$mysqlLogin -p$mysqlPassword $dbName > $dbName-$(date +"%Y-%m-%d").sql
    ;;
esac